# SETTING FILE FOR THE CAROUSEL
#
# AS FOR NOW YOU CAN EDIT THE FOLLOWING:
#
# THE SIZE OF THE CAROUSEL (CAROUSEL IMAGES SIZE WIDTH/ HEIGHT)
# WHETHER TO DISPLAY THE NAVIGATION (LITTLE DOTS IN THE UPPER RIGHT CORNER)
# WHETHER TO DISPLAY THE MENU ENTRIES OF THE CAROUSEL (MENU BELOW THE CAROUSEL)

IMAGE_WIDTH = 960
IMAGE_HEIGHT = 360
NAVIGATION = True
MENU_ENTRIES = True
